from .uploadMediaModel import UploadMediaModel
from .userModel import UserModel
from .talentCategoryModel import TalentCategoryModel
from .talentSubCategoryModel import TalentSubCategoryModel
from .talentDetailsModel import TalentDetailsModel
from .faqModel import FAQModel
from .manageAddressModel import ManageAddressModel
from .termAndConditionModel import TermAndConditionModel
from .bookingTalentModel import BookingTalentModel