# Generated by Django 5.0.4 on 2024-04-30 06:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bust', models.IntegerField(help_text='in inches')),
                ('waist', models.IntegerField(help_text='in inches')),
                ('hips', models.IntegerField(help_text='in inches')),
                ('height_feet', models.IntegerField(help_text='in feet')),
                ('height_inches', models.IntegerField(help_text='in inches')),
                ('weight', models.IntegerField(help_text='in kgs')),
                ('hair_color', models.IntegerField(choices=[(1, 'BROWN'), (2, 'BLACK'), (3, 'GRAY'), (4, 'RED')])),
                ('eye_color', models.IntegerField(choices=[(1, 'BROWN'), (2, 'BLACK'), (3, 'GRAY'), (4, 'GREEN')])),
                ('booking_method', models.IntegerField(choices=[(1, 'PRE BOOK'), (2, 'PAY LATER')])),
                ('portfolio', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('sub_categories', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('cover_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist_app.uploadmediamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Talent details',
            },
        ),
    ]
