# Generated by Django 5.0.4 on 2024-04-30 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0002_talentdetailsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentdetailsmodel',
            name='booking_method',
            field=models.IntegerField(choices=[(1, 'PRE BOOK'), (2, 'PAY LATER')], default=0),
        ),
        migrations.AlterField(
            model_name='talentdetailsmodel',
            name='bust',
            field=models.IntegerField(blank=True, help_text='in inches', null=True),
        ),
        migrations.AlterField(
            model_name='talentdetailsmodel',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist_app.uploadmediamodel'),
        ),
        migrations.AlterField(
            model_name='talentdetailsmodel',
            name='eye_color',
            field=models.IntegerField(choices=[(1, 'BROWN'), (2, 'BLACK'), (3, 'GRAY'), (4, 'GREEN')], default=0),
        ),
        migrations.AlterField(
            model_name='talentdetailsmodel',
            name='hair_color',
            field=models.IntegerField(choices=[(1, 'BROWN'), (2, 'BLACK'), (3, 'GRAY'), (4, 'RED')], default=0),
        ),
        migrations.AlterField(
            model_name='talentdetailsmodel',
            name='height_feet',
            field=models.IntegerField(blank=True, help_text='in feet', null=True),
        ),
        migrations.AlterField(
            model_name='talentdetailsmodel',
            name='height_inches',
            field=models.IntegerField(blank=True, help_text='in inches', null=True),
        ),
        migrations.AlterField(
            model_name='talentdetailsmodel',
            name='hips',
            field=models.IntegerField(blank=True, help_text='in inches', null=True),
        ),
        migrations.AlterField(
            model_name='talentdetailsmodel',
            name='waist',
            field=models.IntegerField(blank=True, help_text='in inches', null=True),
        ),
        migrations.AlterField(
            model_name='talentdetailsmodel',
            name='weight',
            field=models.IntegerField(blank=True, help_text='in kgs', null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_status',
            field=models.IntegerField(blank=True, choices=[(1, 'SIGN_UP_COMPLETED'), (2, 'CATEGORIES ADDED')], null=True),
        ),
    ]
