# Generated by Django 4.2.11 on 2024-05-02 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0004_faqmodel_termandconditionmodel_manageaddressmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTalentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'OFFER SENT'), (2, 'OFFER ACCEPTED'), (2, 'OFFER DECLINED')], null=True)),
                ('offer_price', models.IntegerField(default=0)),
                ('comment', models.TextField(default='')),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.manageaddressmodel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist_app.talentdetailsmodel')),
            ],
            options={
                'db_table': 'bookingDetails',
            },
        ),
    ]
