# Generated by Django 4.2.11 on 2024-05-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0005_bookingtalentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_status',
            field=models.IntegerField(choices=[(1, 'SIGN_UP_COMPLETED'), (2, 'CATEGORIES ADDED')], default=0),
        ),
    ]
