# Generated by Django 4.2.11 on 2024-05-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0006_alter_usermodel_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
