# Generated by Django 4.2.11 on 2024-05-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0010_rename_uuid_chatsessionmodel_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsessionmodel',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
    ]
