# Generated by Django 4.2.11 on 2024-05-07 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0011_alter_chatsessionmodel_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatstoragemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 16, 23, 34, 506215)),
        ),
    ]
