# Generated by Django 4.2.11 on 2024-05-07 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0012_alter_chatstoragemodel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatstoragemodel',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chatstoragemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 17, 0, 3, 198261)),
        ),
    ]
