# Generated by Django 4.2.11 on 2024-05-08 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0013_chatstoragemodel_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatstoragemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 27, 8, 651467)),
        ),
    ]
