# Generated by Django 4.2.11 on 2024-05-08 11:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0014_alter_chatstoragemodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatstoragemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 16, 50, 23, 40311)),
        ),
        migrations.CreateModel(
            name='ReviewAndRatingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('best_liked', models.IntegerField(choices=[(1, 'Punctuality'), (2, 'Clarity'), (3, 'Helpfulness')])),
                ('review', models.TextField()),
                ('rating', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_talent_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review and ratings',
            },
        ),
    ]
