# Generated by Django 4.2.13 on 2024-05-13 07:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0017_alter_chatstoragemodel_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatstoragemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 12, 51, 38, 398141)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'CLIENT'), (2, 'TALENT'), (3, 'ADMIN'), (4, 'SUB ADMIN')], null=True),
        ),
        migrations.CreateModel(
            name='PermissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.IntegerField(choices=[(1, 'Dashboard'), (1, 'Manage customers'), (1, 'Manage artist'), (1, 'Manage Category'), (1, 'Booking Management'), (1, 'Revenue Management'), (1, 'Notification Management'), (1, 'Report Management'), (1, 'Manage Reviews'), (1, 'Manage CMS')])),
                ('can_add_edit', models.BooleanField(default=False)),
                ('can_view', models.BooleanField(default=False)),
                ('can_be_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
    ]
