# Generated by Django 4.2.13 on 2024-05-13 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0018_alter_chatstoragemodel_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='verification_status',
            field=models.IntegerField(choices=[(1, 'ACCEPTED'), (2, 'REJECTED')], default=0),
        ),
        migrations.AlterField(
            model_name='chatstoragemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 14, 30, 1, 341308)),
        ),
        migrations.AlterField(
            model_name='permissionmodel',
            name='module',
            field=models.IntegerField(choices=[(1, 'Dashboard'), (2, 'Manage customers'), (3, 'Manage artist'), (4, 'Manage Category'), (5, 'Booking Management'), (6, 'Revenue Management'), (7, 'Notification Management'), (8, 'Report Management'), (9, 'Manage Reviews'), (10, 'Manage CMS')]),
        ),
    ]
