# Generated by Django 4.2.13 on 2024-05-13 10:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0019_usermodel_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatstoragemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 16, 19, 29, 4433)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='verification_status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'REJECTED')], default=0),
        ),
        migrations.CreateModel(
            name='OperationalSlotsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('day', models.CharField(max_length=100)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Operational slots',
            },
        ),
    ]
