# Generated by Django 4.2.13 on 2024-05-14 06:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0022_alter_chatstoragemodel_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtalentmodel',
            name='talent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_booking_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatstoragemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 12, 24, 32, 622368)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_status',
            field=models.IntegerField(choices=[(1, 'SIGN_UP_COMPLETED'), (2, 'CATEGORIES ADDED'), (3, 'MODEL STATUS ADDED'), (4, 'BOOKING METHOD ADDED')], default=0),
        ),
    ]
