# Generated by Django 4.2.13 on 2024-05-14 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0023_alter_bookingtalentmodel_talent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalslotsmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingtalentmodel',
            name='duration',
            field=models.IntegerField(blank=True, help_text='in hours', null=True),
        ),
        migrations.AlterField(
            model_name='bookingtalentmodel',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'PENDING'), (2, 'ACCEPTED'), (3, 'DECLINED'), (4, 'CANCELLED')], null=True),
        ),
        migrations.AlterField(
            model_name='chatstoragemodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 15, 1, 1, 50410)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'MALE'), (2, 'FEMALE')], null=True),
        ),
    ]
