# Generated by Django 4.2.13 on 2024-05-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0024_operationalslotsmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatstoragemodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
