# Generated by Django 4.2.13 on 2024-05-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0025_alter_chatstoragemodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile_status',
            field=models.IntegerField(choices=[(1, 'SIGN_UP_COMPLETED'), (2, 'CATEGORIES ADDED'), (3, 'MODEL STATUS ADDED'), (4, 'PORTFOLIO ADDED'), (5, 'BOOKING METHOD ADDED')], default=0),
        ),
    ]
