# Generated by Django 4.2.13 on 2024-05-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0027_talentdetailsmodel_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtalentmodel',
            name='services',
            field=models.JSONField(default=list),
        ),
    ]
