# Generated by Django 4.2.13 on 2024-05-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0029_notificationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalslotsmodel',
            name='slots',
            field=models.JSONField(default=dict),
        ),
    ]
