# Generated by Django 4.2.13 on 2024-05-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0030_operationalslotsmodel_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='termandconditionmodel',
            name='privacy_policy',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='termandconditionmodel',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
