# Generated by Django 4.2.13 on 2024-05-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0031_termandconditionmodel_privacy_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'ContactUsModel',
            },
        ),
    ]
