# Generated by Django 4.2.13 on 2024-05-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0032_contactusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentdetailsmodel',
            name='eye_color',
            field=models.IntegerField(blank=True, choices=[(1, 'BROWN'), (2, 'BLACK'), (3, 'GRAY'), (4, 'GREEN')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='talentdetailsmodel',
            name='hair_color',
            field=models.IntegerField(blank=True, choices=[(1, 'BROWN'), (2, 'BLACK'), (3, 'GRAY'), (4, 'RED')], default=0, null=True),
        ),
    ]
