# Generated by Django 4.2.13 on 2024-05-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0034_remove_notificationmodel_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtalentmodel',
            name='counter_offer_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingtalentmodel',
            name='track_booking',
            field=models.IntegerField(blank=True, choices=[(1, 'CLIENT MADE OFFER'), (2, 'TALENT COUNTER OFFERED'), (3, 'TALENT ACCEPTED'), (4, 'TALENT AND CLIENT BOTH ACCEPTED'), (5, 'TALENT REJECTED'), (6, 'CLIENT REJECTED')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingtalentmodel',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'PENDING'), (2, 'COMPLETED'), (3, 'CANCELLED')], null=True),
        ),
    ]
