# Generated by Django 4.2.13 on 2024-05-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0035_bookingtalentmodel_counter_offer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmediamodel',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingtalentmodel',
            name='track_booking',
            field=models.IntegerField(blank=True, choices=[(1, 'CLIENT MADE OFFER'), (2, 'TALENT COUNTER OFFERED'), (3, 'TALENT AND CLIENT BOTH ACCEPTED'), (4, 'TALENT REJECTED'), (5, 'CLIENT REJECTED')], null=True),
        ),
    ]
