# Generated by Django 4.2.13 on 2024-05-17 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0036_uploadmediamodel_is_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notification_type', models.IntegerField(choices=[(1, 'OFFER ACCEPTED BY TALENT'), (2, 'OFFER CANCELLED BY TALENT'), (3, 'TRANSACTION SUCCESS BY CLIENT'), (4, 'OFFER CANCELLED BY TALENT')])),
                ('title', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'App Notifications',
            },
        ),
    ]
