# Generated by Django 4.2.13 on 2024-05-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0037_appnotificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotificationmodel',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'OFFER ACCEPTED'), (2, 'OFFER CANCELLED BY TALENT'), (3, 'TRANSACTION SUCCESS BY CLIENT'), (4, 'PAYMENT RECEIVED BY CLIENT'), (4, 'OFFER CANCELLED BY TALENT')]),
        ),
    ]
