# Generated by Django 4.2.13 on 2024-05-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0038_alter_appnotificationmodel_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='experience',
        ),
    ]
