# Generated by Django 4.2.13 on 2024-05-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0039_remove_usermodel_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='experience',
            field=models.IntegerField(blank=True, choices=[(1, '0-6 months'), (2, '6 months to 1 year'), (3, '1+ years'), (4, '2+ years'), (5, '3+ years'), (6, '4+ years')], null=True),
        ),
    ]
