# Generated by Django 4.2.13 on 2024-05-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0040_usermodel_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='nationality',
            field=models.CharField(default='', max_length=100),
        ),
    ]
