# Generated by Django 4.2.13 on 2024-05-18 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0041_usermodel_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='nationality',
        ),
    ]
