# Generated by Django 4.2.13 on 2024-05-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0043_remove_talentdetailsmodel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentdetailsmodel',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
