# Generated by Django 4.2.13 on 2024-05-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0044_talentdetailsmodel_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtalentmodel',
            name='track_booking',
            field=models.IntegerField(blank=True, choices=[(1, 'CLIENT MADE OFFER'), (2, 'TALENT COUNTER OFFERED'), (3, 'TALENT AND CLIENT BOTH ACCEPTED'), (4, 'TALENT REJECTED'), (5, 'CLIENT REJECTED'), (6, 'MARKED COMPLETED')], null=True),
        ),
    ]
