# Generated by Django 4.2.13 on 2024-05-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0045_alter_bookingtalentmodel_track_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalslotsmodel',
            options={'ordering': ['-id']},
        ),
    ]
