# Generated by Django 4.2.13 on 2024-05-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0046_alter_operationalslotsmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalslotsmodel',
            options={'ordering': ['-date']},
        ),
    ]
