# Generated by Django 4.2.13 on 2024-05-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0047_alter_operationalslotsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtalentmodel',
            name='rating_given',
            field=models.BooleanField(default=False),
        ),
    ]
