# Generated by Django 4.2.13 on 2024-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0048_bookingtalentmodel_rating_given'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtalentmodel',
            old_name='rating_given',
            new_name='rating_by_client',
        ),
        migrations.AddField(
            model_name='bookingtalentmodel',
            name='rating_by_talent',
            field=models.BooleanField(default=False),
        ),
    ]
