# Generated by Django 4.2.13 on 2024-05-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0049_rename_rating_given_bookingtalentmodel_rating_by_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewandratingsmodel',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artist_app.bookingtalentmodel'),
        ),
    ]
