# Generated by Django 4.2.13 on 2024-05-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0050_reviewandratingsmodel_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewandratingsmodel',
            name='booking',
        ),
    ]
