# Generated by Django 4.2.13 on 2024-05-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0051_remove_reviewandratingsmodel_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewandratingsmodel',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artist_app.bookingtalentmodel'),
        ),
        migrations.AddField(
            model_name='reviewandratingsmodel',
            name='given_by',
            field=models.IntegerField(blank=True, choices=[(1, 'client'), (2, 'talent')], null=True),
        ),
    ]
