# Generated by Django 4.2.13 on 2024-05-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0054_talentcategorymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageaddressmodel',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manageaddressmodel',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manageaddressmodel',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
