# Generated by Django 4.2.13 on 2024-05-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0058_contactusmodel_data_contactusmodel_privacy_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageaddressmodel',
            name='address_location',
        ),
        migrations.RemoveField(
            model_name='manageaddressmodel',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='manageaddressmodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='manageaddressmodel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='manageaddressmodel',
            name='house_flat_block_no',
        ),
        migrations.RemoveField(
            model_name='manageaddressmodel',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='manageaddressmodel',
            name='phone_no_manage_address',
        ),
        migrations.RemoveField(
            model_name='manageaddressmodel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='manageaddressmodel',
            name='street_no',
        ),
    ]
