# Generated by Django 4.2.13 on 2024-05-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0059_remove_manageaddressmodel_address_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageaddressmodel',
            name='address_location',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='manageaddressmodel',
            name='address_type',
            field=models.IntegerField(blank=True, choices=[(1, 'HOME'), (2, 'WORK'), (3, 'OTHER')], null=True),
        ),
        migrations.AddField(
            model_name='manageaddressmodel',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manageaddressmodel',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manageaddressmodel',
            name='house_flat_block_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manageaddressmodel',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manageaddressmodel',
            name='phone_no_manage_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manageaddressmodel',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='manageaddressmodel',
            name='street_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
