# Generated by Django 4.2.13 on 2024-05-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0060_manageaddressmodel_address_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsessionmodel',
            name='session_id',
        ),
    ]
