# Generated by Django 4.2.13 on 2024-05-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0061_remove_chatsessionmodel_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionmodel',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
