# Generated by Django 4.2.13 on 2024-05-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0062_chatsessionmodel_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusmodel',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
