# Generated by Django 4.2.13 on 2024-05-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0063_contactusmodel_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtalentmodel',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
