# Generated by Django 4.2.13 on 2024-06-03 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0064_bookingtalentmodel_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotificationmodel',
            name='booking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artist_app.bookingtalentmodel'),
        ),
        migrations.AddField(
            model_name='bookingtalentmodel',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentdetailsmodel',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
