# Generated by Django 4.2.13 on 2024-06-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0065_appnotificationmodel_booking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
