# Generated by Django 5.0.4 on 2024-06-04 12:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artist_app", "0066_usermodel_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talentdetailsmodel",
            name="booking_method",
        ),
    ]
