# Generated by Django 5.0.4 on 2024-06-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artist_app", "0067_remove_talentdetailsmodel_booking_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentdetailsmodel",
            name="booking_method",
            field=models.JSONField(default=list),
        ),
    ]
