# Generated by Django 5.0.4 on 2024-06-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artist_app", "0069_remove_talentdetailsmodel_booking_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentdetailsmodel",
            name="booking_method",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="talentdetailsmodel",
            name="tags",
            field=models.JSONField(default=list),
        ),
    ]
