# Generated by Django 5.0.4 on 2024-06-05 05:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artist_app", "0070_talentdetailsmodel_booking_method_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talentdetailsmodel",
            name="booking_method",
        ),
        migrations.RemoveField(
            model_name="talentdetailsmodel",
            name="tags",
        ),
    ]
