# Generated by Django 5.0.4 on 2024-06-05 05:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artist_app", "0071_remove_talentdetailsmodel_booking_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentdetailsmodel",
            name="booking_method",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="talentdetailsmodel",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=list, size=None
            ),
        ),
    ]
