# Generated by Django 5.0.4 on 2024-06-05 05:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artist_app", "0072_talentdetailsmodel_booking_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talentdetailsmodel",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=list, size=None
            ),
        ),
    ]
