# Generated by Django 5.0.4 on 2024-06-06 07:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artist_app", "0074_remove_reviewandratingsmodel_best_liked"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewandratingsmodel",
            name="best_liked",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=list, size=None
            ),
        ),
    ]
