# Generated by Django 4.2.13 on 2024-06-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0076_bookingtalentmodel_client_marked_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
