# Generated by Django 4.2.13 on 2024-06-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0078_remove_permissionmodel_can_add_edit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionmodel',
            name='is_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionmodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionmodel',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permissionmodel',
            name='is_view',
            field=models.BooleanField(default=False),
        ),
    ]
