# Generated by Django 4.2.13 on 2024-06-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0079_permissionmodel_is_add_permissionmodel_is_delete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColourPreferencesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('preference_type', models.IntegerField(choices=[(1, 'HAIR COLOUR'), (2, 'EYE COLOUR')])),
            ],
            options={
                'db_table': 'Colour preferences',
            },
        ),
        migrations.AlterField(
            model_name='permissionmodel',
            name='module',
            field=models.IntegerField(choices=[(1, 'Dashboard'), (2, 'Manage customers'), (3, 'Manage artist'), (4, 'Manage Category'), (5, 'Booking Management'), (6, 'Revenue Management'), (7, 'Notification Management'), (8, 'Report Management'), (9, 'Manage Reviews'), (10, 'Manage CMS'), (12, 'Setting'), (13, 'Logout')]),
        ),
    ]
