# Generated by Django 4.2.13 on 2024-06-11 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0081_remove_talentdetailsmodel_eye_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentdetailsmodel',
            name='eye_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_colour_fk', to='artist_app.colourpreferencesmodel'),
        ),
        migrations.AddField(
            model_name='talentdetailsmodel',
            name='hair_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hair_colour_fk', to='artist_app.colourpreferencesmodel'),
        ),
    ]
