# Generated by Django 4.2.13 on 2024-06-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0082_talentdetailsmodel_eye_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtalentmodel',
            name='booking_type',
            field=models.IntegerField(choices=[(1, 'PRE BOOK'), (2, 'PAY LATER')], default=2),
        ),
    ]
