# Generated by Django 4.2.13 on 2024-06-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0083_bookingtalentmodel_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotificationmodel',
            name='notification_type',
            field=models.IntegerField(default=2),
        ),
    ]
