# Generated by Django 4.2.13 on 2024-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0084_alter_appnotificationmodel_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
