# Generated by Django 4.2.13 on 2024-10-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0085_usermodel_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionmodel',
            name='testing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
